var classes = [
    {
        "name": "ReportController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all_reports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all_reports_for_timeframe",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save_report",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "is_analyzed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get_report_by_hash",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 8,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 131,
        "vocabulary": 47,
        "volume": 727.65,
        "difficulty": 5.07,
        "effort": 3689.02,
        "level": 0.2,
        "bugs": 0.24,
        "time": 205,
        "intelligentContent": 143.53,
        "number_operators": 22,
        "number_operands": 109,
        "number_operators_unique": 4,
        "number_operands_unique": 43,
        "cloc": 0,
        "loc": 45,
        "lloc": 45,
        "mi": 43.49,
        "mIwoC": 43.49,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.4,
        "relativeSystemComplexity": 17.4,
        "totalStructuralComplexity": 96,
        "totalDataComplexity": 8.4,
        "totalSystemComplexity": 104.4,
        "package": "\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "ReportSessionController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reports_by_session",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "user_has_reports",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 36,
        "vocabulary": 13,
        "volume": 133.22,
        "difficulty": 5.56,
        "effort": 740.09,
        "level": 0.18,
        "bugs": 0.04,
        "time": 41,
        "intelligentContent": 23.98,
        "number_operators": 11,
        "number_operands": 25,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 30,
        "lloc": 30,
        "mi": 52.36,
        "mIwoC": 52.36,
        "commentWeight": 0,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 17,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 51,
        "package": "\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "FileFactory",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "uploadFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "downloadFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "TxtUpload",
            "XmlUpload",
            "HtmlUpload",
            "CsvDownload",
            "XmlDownload",
            "XlsxDownload"
        ],
        "parents": [],
        "lcom": 2,
        "length": 43,
        "vocabulary": 19,
        "volume": 182.66,
        "difficulty": 3,
        "effort": 547.98,
        "level": 0.33,
        "bugs": 0.06,
        "time": 30,
        "intelligentContent": 60.89,
        "number_operators": 11,
        "number_operands": 32,
        "number_operators_unique": 3,
        "number_operands_unique": 16,
        "cloc": 0,
        "loc": 41,
        "lloc": 41,
        "mi": 48.04,
        "mIwoC": 48.04,
        "commentWeight": 0,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CsvDownload",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "export",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ExportFile"
        ],
        "parents": [],
        "lcom": 1,
        "length": 72,
        "vocabulary": 33,
        "volume": 363.2,
        "difficulty": 2.23,
        "effort": 808.4,
        "level": 0.45,
        "bugs": 0.12,
        "time": 45,
        "intelligentContent": 163.18,
        "number_operators": 3,
        "number_operands": 69,
        "number_operators_unique": 2,
        "number_operands_unique": 31,
        "cloc": 0,
        "loc": 21,
        "lloc": 21,
        "mi": 52.96,
        "mIwoC": 52.96,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 0.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "XlsxDownload",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "export",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "ExportFile",
            "SimpleXLSXGen"
        ],
        "parents": [],
        "lcom": 1,
        "length": 65,
        "vocabulary": 29,
        "volume": 315.77,
        "difficulty": 1.13,
        "effort": 355.24,
        "level": 0.89,
        "bugs": 0.11,
        "time": 20,
        "intelligentContent": 280.68,
        "number_operators": 2,
        "number_operands": 63,
        "number_operators_unique": 1,
        "number_operands_unique": 28,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 56.71,
        "mIwoC": 56.71,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 4.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 8.33,
        "package": "\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "XmlDownload",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "export",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "ExportFile"
        ],
        "parents": [],
        "lcom": 1,
        "length": 171,
        "vocabulary": 70,
        "volume": 1048.11,
        "difficulty": 2.46,
        "effort": 2581.16,
        "level": 0.41,
        "bugs": 0.35,
        "time": 143,
        "intelligentContent": 425.6,
        "number_operators": 61,
        "number_operands": 110,
        "number_operators_unique": 3,
        "number_operands_unique": 67,
        "cloc": 0,
        "loc": 39,
        "lloc": 39,
        "mi": 44.01,
        "mIwoC": 44.01,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 0.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "HtmlUpload",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 1.75,
        "effort": 45.24,
        "level": 0.57,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 14.77,
        "number_operators": 3,
        "number_operands": 7,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 64.97,
        "mIwoC": 64.97,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "TxtUpload",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 7,
        "vocabulary": 5,
        "volume": 16.25,
        "difficulty": 1.67,
        "effort": 27.09,
        "level": 0.6,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 9.75,
        "number_operators": 2,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 67.09,
        "mIwoC": 67.09,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "XmlUpload",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 23,
        "vocabulary": 12,
        "volume": 82.45,
        "difficulty": 4,
        "effort": 329.82,
        "level": 0.25,
        "bugs": 0.03,
        "time": 18,
        "intelligentContent": 20.61,
        "number_operators": 7,
        "number_operands": 16,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 58.93,
        "mIwoC": 58.93,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 5,
        "package": "\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Report",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 121,
        "vocabulary": 33,
        "volume": 610.37,
        "difficulty": 3.26,
        "effort": 1988.63,
        "level": 0.31,
        "bugs": 0.2,
        "time": 110,
        "intelligentContent": 187.34,
        "number_operators": 20,
        "number_operands": 101,
        "number_operators_unique": 2,
        "number_operands_unique": 31,
        "cloc": 0,
        "loc": 27,
        "lloc": 27,
        "mi": 49,
        "mIwoC": 49,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 37,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 37,
        "package": "\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Text",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get_text",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 68.01,
        "mIwoC": 68.01,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Char",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get_count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frequency",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frequency_in_percentage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Frequency",
            "Counter"
        ],
        "parents": [],
        "lcom": 1,
        "length": 64,
        "vocabulary": 25,
        "volume": 297.21,
        "difficulty": 5.63,
        "effort": 1671.79,
        "level": 0.18,
        "bugs": 0.1,
        "time": 93,
        "intelligentContent": 52.84,
        "number_operators": 19,
        "number_operands": 45,
        "number_operators_unique": 5,
        "number_operands_unique": 20,
        "cloc": 0,
        "loc": 33,
        "lloc": 33,
        "mi": 49.16,
        "mIwoC": 49.16,
        "commentWeight": 0,
        "kanDefect": 0.61,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.63,
        "relativeSystemComplexity": 2.63,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 6.5,
        "totalSystemComplexity": 10.5,
        "package": "\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Palindrome",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sort_by_length",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get_count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Sorter",
            "Counter"
        ],
        "parents": [],
        "lcom": 1,
        "length": 34,
        "vocabulary": 13,
        "volume": 125.81,
        "difficulty": 6.88,
        "effort": 864.98,
        "level": 0.15,
        "bugs": 0.04,
        "time": 48,
        "intelligentContent": 18.3,
        "number_operators": 12,
        "number_operands": 22,
        "number_operators_unique": 5,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 29,
        "lloc": 29,
        "mi": 52.86,
        "mIwoC": 52.86,
        "commentWeight": 0,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.33,
        "relativeSystemComplexity": 3.33,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 10,
        "package": "\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Sentence",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sort_by_length",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get_count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Sorter",
            "Counter"
        ],
        "parents": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 13,
        "volume": 107.31,
        "difficulty": 5.94,
        "effort": 637.17,
        "level": 0.17,
        "bugs": 0.04,
        "time": 35,
        "intelligentContent": 18.07,
        "number_operators": 10,
        "number_operands": 19,
        "number_operators_unique": 5,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 25,
        "lloc": 25,
        "mi": 55.02,
        "mIwoC": 55.02,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.33,
        "relativeSystemComplexity": 3.33,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 10,
        "package": "\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Word",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get_array_words",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sort_by_length",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get_count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "most_used",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Sorter",
            "Counter",
            "UsageMeter"
        ],
        "parents": [],
        "lcom": 1,
        "length": 65,
        "vocabulary": 23,
        "volume": 294.03,
        "difficulty": 7.41,
        "effort": 2179.29,
        "level": 0.13,
        "bugs": 0.1,
        "time": 121,
        "intelligentContent": 39.67,
        "number_operators": 23,
        "number_operands": 42,
        "number_operators_unique": 6,
        "number_operands_unique": 17,
        "cloc": 0,
        "loc": 43,
        "lloc": 43,
        "mi": 46.68,
        "mIwoC": 46.68,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3.2,
        "relativeSystemComplexity": 4.2,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 16,
        "totalSystemComplexity": 21,
        "package": "\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    }
]